### PR TITLE
Check for user-given type when encountering extra columns during parsing

### LINKED ISSUE #1021: Bug with setting column type
Reproducer:
```
julia> str = """
       1 2 3
       1 2
       1 2 3 4
       1
       1 2 3 4 5
       """
"1 2 3\n1 2\n1 2 3 4\n1\n1 2 3 4 5\n"

julia> CSV.read(IOBuffer(str), DataFrame, delim=" ", header=false, types=String, silencewarnings=true)
5×5 DataFrame
 Row │ Column1  Column2  Column3  Column4  Column5
     │ String   String?  String?  Int64?   Int64?
─────┼─────────────────────────────────────────────
   1 │ 1        2        3        missing  missing
   2 │ 1        2        missing  missing  missing
   3 │ 1        2        3              4  missing
   4 │ 1        missing  missing  missing  missing
   5 │ 1        2        3              4        5
```
As you can see columns 4 and 5 get an incorrect column type.

### PR DESCRIPTION
**Pull request by nickrobinson251**
- close #1021 
- Before this PR, when we encounter a new/extra column we were always relying on type detection -- by setting this extra column's type to `NeedsTypeDetection` -- or, if streaming, setting it to a string type. This meant we were ignoring the case where a user had actually provided the type for this "extra" column, e.g. by setting `types=T`, to request all columns to have eltype `T`.
- This PR largely factors out the Column-type setting logic used when initalising columns in `Context` to be available to be reused by `File` when a new/extra column is encountered during parsing.

### CODE REVIEW

File: src/context.jl [hunk 1]
```diff
@@ -79,19 +79,79 @@ function checkvaliddelim(delim)
...
+
+function initialize_column(i, types::AbstractDict, names, stringtype, streaming::Bool, options)
+    defaultT = streaming ? Union{stringtype, Missing} : NeedsTypeDetection
+    T = getordefault(types, names[i], i, defaultT)
+    col = Column(T, options)
+    return col
+end
+
+function initialize_column(i, types::Function, names, stringtype, streaming::Bool, options)
+    defaultT = streaming ? Union{stringtype, Missing} : NeedsTypeDetection
```
Comment (nickrobinson251) [inline src/context.jl:141]: this logic is repeated in a few of these methods, so i considered pulling it out but that actually leads to it being repeated a few places further apart in the code which seemed less nice than it being contained only in the methods of this one function

File: src/context.jl [hunk 2]
```diff
@@ -119,6 +179,11 @@ struct Context
     debug::Bool
     tempfile::Union{String, Nothing}
     streaming::Bool
+    types::Union{Nothing, Type, AbstractVector, AbstractDict, Function}
```
Comment (nickrobinson251) [inline src/context.jl:182]: the least nice thing about this PR, in my view, is that (i) it requires yet-another field in `Context` and (ii) one with this long-winded type `Union{Nothing, Type, AbstractVector, AbstractDict, Function}`

On (i), i couldn't think of another way to pass this info through to the parsing context... it's kinda what `Context` is for.

On (ii), i considered whether when constructing the `Context` we could construct a new `types` with a fixed type e.g. `types::Vector`, but i think that actually becomes more tricky, since we always want the same flexibility with `types` whether we're using it _before_ parsing (like in Context) or _during_ parsing (like when we hit an extra column), so i decided against this.

Thoughts welcome!

File: src/file.jl [hunk 3]
```diff
@@ -684,17 +684,18 @@ Base.@propagate_inbounds function parserow(startpos, row, numwarnings, ctx::Cont
                 # extra columns on this row, let's widen
                 ctx.silencewarnings || toomanycolumns(ncols, rowoffset + row)
                 j = i + 1
-                T = ctx.streaming ? Union{ctx.stringtype, Missing} : NeedsTypeDetection
                 while pos <= len && !Parsers.newline(code)
-                    col = Column(T, ctx.options)
+                    col = initialize_column(j, ctx)
                     col.anymissing = ctx.streaming || rowoffset == 0 && row > 1 # assume all previous rows were missing
                     col.pool = ctx.pool
+                    # TODO: Do we need to check `nonstandardtype(T)` and potentially create a `Context` an updated `customtypes`?
```
Comment (nickrobinson251) [inline src/file.jl:691]: thoughts, @quinnj ?

File: src/context.jl (hunk 2 above)
Comment (quinnj) [reply src/context.jl:182]: This is probably fine. Still reviewing the rest of the PR

File: src/file.jl (hunk 3 above)
Comment (quinnj) [reply src/file.jl:691]: Oof, this is rough. This is exposing a big design issue w/ how we're currently doing parsing. And it's not obvious how to fix. Unfortunately just creating a new context isn't quite enough because we're cheating a little and passing `ctx.customtypes` to `parsechunk!` so that it gets specialized. So we would need to recall `parsechunk` _and_ pass the new customtypes, and my brain can't quite wrap around how this would affect the multithreaded context we're in.

BUT, I think this fix is good for now, but we maybe just need to make a note that non-standard types aren't supported on widened columns.

**Review by quinnj — APPROVED** [review]

**Comment by quinnj** [comment]
Yeah, this looks good overall; but I think as we do the larger refactor with @Drvi's work, we should think more broadly about how to address the non-standard type problem and if we can come up with something clever there.

File: src/file.jl (hunk 3 above)
Comment (nickrobinson251) [reply src/file.jl]: ah, yeah this is complex -- i agree it's not obvious how to support it and it does seem _very_ niche.

I've added an `@error` log to inform us if we are ever in this scenario and tell a user parsing will probably fail
https://github.com/JuliaData/CSV.jl/pull/1023/commits/e00fe5e9fcd26c7076280ad7b69e2d519040012f

**Comment by quinnj** [comment]
Looks like there's a real test failure happening during column widening.

**Comment by nickrobinson251** [comment]
Glad i waited for Ci! Issues should be fixed now.
