### PR TITLE
Fix reading gzipped file in Julia 1.11 on Windows

### LINKED ISSUE #1137: CSV.File failing for gzipped file in Julia 1.11-rc
``
[test3.dat.gz](https://github.com/user-attachments/files/16286492/test3.dat.gz)
`
```
julia> lmadata = CSV.File(raw"C:\Users\oscar\Documents\Work\Julia\test3.dat.gz")
ERROR: IOError: unlink("C:\\Users\\oscar\\AppData\\Local\\Temp\\jl_F294.tmp"): permission denied (EACCES)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:106 [inlined]
 [2] unlink(p::String)
   @ Base.Filesystem .\file.jl:1105
 [3] rm(path::String; force::Bool, recursive::Bool)
   @ Base.Filesystem .\file.jl:283
 [4] rm
   @ .\file.jl:273 [inlined]
 [5] CSV.File(ctx::CSV.Context, chunking::Bool)
   @ CSV C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:344
 [6] File
   @ C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:227 [inlined]
 [7] #File#32
   @ C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:223 [inlined]
 [8] CSV.File(source::String)
   @ CSV C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:162

julia> lmadata = CSV.File(raw"C:\Users\oscar\Documents\Work\Julia\test3.dat.gz",header=false,delim=' ', ignorerepeated=true)
ERROR: IOError: unlink("C:\\Users\\oscar\\AppData\\Local\\Temp\\jl_B18B.tmp"): permission denied (EACCES)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:106 [inlined]
 [2] unlink(p::String)
   @ Base.Filesystem .\file.jl:1105
 [3] rm(path::String; force::Bool, recursive::Bool)
   @ Base.Filesystem .\file.jl:283
 [4] rm
   @ .\file.jl:273 [inlined]
 [5] CSV.File(ctx::CSV.Context, chunking::Bool)
   @ CSV C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:344
 [6] File
   @ C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:227 [inlined]
 [7] #File#32
   @ C:\Users\oscar\.julia\packages\CSV\cwX2w\src\file.jl:223 [inlined]
 [8] top-level scope
   @ REPL[45]:1

```

Julia Version 1.11.0-rc1
Commit 3a35aec36d (2024-06-25 10:23 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, tigerlake)
Threads: 16 default, 0 interactive, 8 GC (on 16 virtual cores)
Environment:
  JULIA_EDITOR = code

CSV v0.10.14

dat.gz file is attached.

Note: it works fine on the raw data.

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #1137

On Julia 1.11 the underlying memory needs to be finalized to unmmap the file.
Ref: https://github.com/JuliaLang/julia/pull/54210

### CODE REVIEW

**Comment by nhz2** [comment]
@longemen3000 @oscarvdvelde @JakeZw This PR is ready for review now

File: src/file.jl [hunk 1]
```diff
@@ -336,8 +336,14 @@ function File(ctx::Context, @nospecialize(chunking::Bool=false))
     ctx.debug && println("types after parsing: $types, pool = $(ctx.pool)")
     # for windows, it's particularly finicky about throwing errors when you try to modify an mmapped file
     # so we just want to make sure we finalize the input buffer so users don't run into surprises
+    # on Julia 1.11 the underlying memory needs to be finalized to unmmap the file.
+    # Ref: https://github.com/JuliaLang/julia/pull/54210
     if !chunking && Sys.iswindows() && ctx.stringtype !== PosLenString
-        finalize(ctx.buf)
+        if VERSION ≥ v"1.11"
```
Comment (quinnj) [inline src/file.jl:342]: 👍

**Review by quinnj — APPROVED** [review]
Thanks for the fixes @nhz2!
