### PR TITLE
fix INT128_MIN write

### LINKED ISSUE #1151: INT128_MIN write error
Writing INT128_MIN produces `-/)0/,//(-,*0,*'.-/)-/*()-0-)/+((,/0+).(` instead of valid output. Logs:
```julia
julia> df = DataFrame(a = Int128[])
0×1 DataFrame
 Row │ a      
     │ Int128 
─────┴────────

julia> push!(df, [Int128(-170141183460469231731687303715884105728)])
1×1 DataFrame
 Row │ a                                 
     │ Int128                            
─────┼───────────────────────────────────
   1 │ -1701411834604692317316873037158…

julia> CSV.write("a.csv", df)
"a.csv"

julia> CSV.read("a.csv", DataFrame)
┌ Warning: thread = 1 warning: parsed expected 1 columns, but didn't reach end of line around data row: 1. Parsing extra columns and widening final columnset
└ @ CSV ~/.julia/packages/CSV/XLcqT/src/file.jl:593
1×5 DataFrame
 Row │ a        Column2  Column3  Column4              Column5 
     │ String7  String7  String3  String31             String7 
─────┼─────────────────────────────────────────────────────────
   1 │ -/)0/    //(-     *0       *'.-/)-/*()-0-)/+((  /0+).(

```

### PR DESCRIPTION
**Pull request by belous-dp**
this PR fixes #1151

### CODE REVIEW

File: src/write.jl [hunk 1]
```diff
@@ -435,7 +435,7 @@ end
 
 function writecell(buf, pos, len, io, x::Integer, opts)
     if x < 0
-        x *= -1
+        x = unsigned(-(x + 1)) + 1
```
Comment (nhz2) [inline src/write.jl:438]:
```suggestion
        x = Base.uabs(x)
```

This should fix the `BigInt` issue.

**Comment by nhz2** [comment]
This breaks writing `BigInt`:

```julia
df = DataFrame(a = BigInt[])
push!(df, [big(-170141183460469231731687303715884105728)])
CSV.write("a.csv", df)
ERROR: MethodError: no method matching Unsigned(::BigInt)
The type `Unsigned` exists, but no method is defined for this combination of argument types when trying to construct it.
```

I think replacing

File: test/write.jl [hunk 2]
```diff
@@ -195,6 +195,12 @@ Base.string(x::AF) = string(x.f)
             [StructType(Date("2021-12-01"), "string 1", 123.45), StructType(Date("2021-12-02"), "string 2", 456.78)],
             (header=["Date Column", "String Column", "Number Column"],),
             "Date Column,String Column,Number Column\n2021-12-01,string 1,123.45\n2021-12-02,string 2,456.78\n"
+        ),
+        # 1151
+        (
+            [(a=Int128(-170141183460469231731687303715884105728),)],
+            NamedTuple(),
+            "a\n-170141183460469231731687303715884105728\n"
         )
```
Comment (nhz2) [inline test/write.jl:204]: It would be good to add a test with `BigInt` as well to avoid future regressions.

Comment (belous-dp) [reply test/write.jl]: done

**Review by nhz2 — APPROVED** [review]
Thank you for fixing this. I did a basic benchmark with:

```julia
using BenchmarkTools, CSV
@btime CSV.writecell($(zeros(UInt8,1000)), 1, 100, $(IOBuffer()), -1234567890, nothing)
```

And I don't see a major performance regression, so I think this is ready to be merged.

**Review by quinnj — APPROVED** [review]
Thanks! Sorry for hte slow review.
